---
name: Commit workflow
on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: ruby setup (mac)
        if: matrix.os == 'macOS-latest'
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
      - name: Install dependencies
        run: sudo apt-get install -y gettext
        if: matrix.os == 'ubuntu-latest'
      - name: asdf plugin test
        uses: asdf-vm/actions/plugin-test@v3
        with:
          command: nvim --version
